### ISSUE TITLE
Documentation checklist for loc

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-l10n#26]
Documenting all of the pieces of the puzzle

* [ ] VS Code website docs - continuing here https://github.com/microsoft/vscode-docs/issues/5774
* [x] VS Code website API docs (requires finalization of API)
* [x] vscode-l10n READMEs
  * [x] vscode API linked
  * [x] `@vscode/l10n-dev`
  * [x] `@vscode/l10n`
  * [x] package.nls.json blurb and link to VS Code website docs
* [x] code docs (CLI help, typings, comments)
* [x] vscode-extensions-samples (PR: https://github.com/microsoft/vscode-extension-samples/pull/721)
